{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "ecommerce-store.fullname" . }}-quota
  labels:
    {{- include "ecommerce-store.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
    requests.storage: {{ .Values.quota.requestsStorage | quote }}
{{- end }}
