{{- if eq .Values.engine "woocommerce" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-store.fullname" . }}-secrets
  labels:
    {{- include "ecommerce-store.labelsWoo" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ required "secrets.mysqlRootPassword is required" .Values.secrets.mysqlRootPassword | quote }}
  mysql-password: {{ required "secrets.mysqlPassword is required" .Values.secrets.mysqlPassword | quote }}
  wp-admin-password: {{ required "secrets.wpAdminPassword is required" .Values.secrets.wpAdminPassword | quote }}
{{- end }}
